# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

if ( Media >=7) {
   "Aprovado!!"
}

else{
    "Reprovado :("
}


Se ( Media >=7 )entao{
    aprovado!!
}
se não {
    reprovado!!
}
fim_se