# -*- coding: utf-8 -*-
"""08-02

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fs4MunMXaY_2jO0XBIICUgMeTfO0iQEw

1) Leia dois números, faça a soma e apresente caso seja maior que 15.
"""

nota1 = float(input("Digite a primeira nota"))
nota2 = float(input("Digite a segunda nota"))

xb = nota1 + nota2 > 15
print (xb)

"""2) Faça um programa que recebendo um valor inteiro, informe se o número é positivo,
negativo ou neutro.
"""

f1 = float(input("Digite um numero: "))
if f1 > 0:
    print("positivo")
elif f1 == 0:
    print("neutro")
else:
     print ("negativo")

"""3) Leia a idade e informe se a pessoa é maior ou menor de idade"""

idade = float(input(Digite a idade:))
if idade >= 18:
  print("maior idade")
else:
  print("menor idade")

""" 4) Faça um programa que pergunte a temperatura atual para o usuário e mostre uma
mensagem na tela dizendo se está “quente”, “frio” ou “agradável”.

"""

temperatura = float(input("Quantos Graus esta?:"))
if temperatura >=18:
  print("agradavel")
elif temperatura>= 26:
    print ("Quente")
else:
  print("frio")

"""5) Faça um programa em linguagem Python que leia dois números inteiros e informe
se estes são iguais ou diferentes.

"""

n1 = float(input("Digite o primeiro numero:"))
n2 = float(input("Digite o segundo numero:"))

if n1==n2:
  print("os numeros sao iguais")
else:
  print("os  numeros sao diferentes" )

"""6. Escreva um programa que verifique a validade de uma senha fornecida pelo
usuário. A senha válida é o número 1234. Devem ser impressas as seguintes
mensagens:
 ACESSO PERMITIDO caso a senha seja válida.
 ACESSO NEGADO caso a senha seja inválida.
"""

rsp = float(input("Digite sua senha:"))

if rsp ==1234:
  print("Acesso permitido!")
else:
  print("Acesso negado :c")

"""7. Ler duas notas de um aluno, efetuar a média aritmética e, se a média for maior ou
igual a 7, informar que o aluno foi aprovado; se a média for maior ou igual a 5 mas
menor do que 7, informar que o aluno está de exame; se a média for menor do que
5 informar que o aluno foi reprovado.
"""

nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))

if (nota1 + nota2) /2 >= 7:
  print("Aprovado")
elif (nota1 + nota2)/2 <=6.9 and nota1 +nota2 >= 5.1:
  print("Exame")
else:
  print("Reprovado")

"""8. Desenvolva um programa que recebe do usuário o placar de um jogo de futebol (os
gols de cada time) e informe se o resultado foi um empate, se a vitória foi do
primeiro time ou do segundo time.

"""

time1 = float(input("Quantos gols time 1 fez? "))
time2 = float(input("Quantos gols time 2 fez? "))

if time1 > time2:
  print("a vitoria é do time 1")

elif time1 ==time2:
  print("Houve um empate")

else:
  print("Time 2 ganhou")

"""9. Faça um Programa que pergunte em que turno você estuda. Peça para digitar Matutino ou V-Vespertino ou N- Noturno. Imprima a mensagem "Bom Dia!", "Boa
Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso.
"""

trn = str(input("Qual turno você estuda? "))

if trn == "manha":
  print("Bom dia!!")
elif trn =="tarde":
  print("Boa tarde!!")
elif trn==noite:
  print("Boa noite!! ")
else:
  print("Valor invalido :c")

"""10. Faça um programa que solicite ao usuário sua idade, depois disso, exiba a
classificação etária de acordo com as faixas de valores:
 Criança para 0 até 11 anos;
 Adolescente para 12 até 18 anos;
 Jovem para 19 até 24 anos;
 Adulto para 25 até 40 anos;
 Meia Idade para 41 até 60 anos;
 Idoso acima de 60 anos.

"""

idd = float(input("Informe a idade: "))
if idd > 60:
  print("Idoso")
elif idd >= 41 :
  print("Meia idade")
elif idd >=25 :
  print("Adulto")
elif idd >=19 :
  print("Jovem")
elif idd >12 :
  print("Adolescente")
else:
  print("Criança")

"""11. As Organizações Tabajara resolveram dar um aumento de salário aos seus
colaboradores e lhe contrataram para desenvolver o programa que calculará os
reajustes. Faça um programa que recebe o salário de um colaborador e o reajuste
segundo o seguinte critério, baseado no salário atual:
 salários até R$ 280,00 (incluindo) : aumento de 20%
 salários entre R$ 280,00 e R$ 700,00 : aumento de 15%
 salários entre R$ 700,00 e R$ 1500,00 : aumento de 10%
 salários de R$ 1500,00 em diante : aumento de 5%
Após o aumento ser realizado, informe na tela:
 o salário antes do reajuste;
 o percentual de aumento aplicado;
 o valor do aumento;
 o novo salário, após o aumento.
"""

def calcular_aumento(salario):
    if salario <= 280:
        percentual_aumento = 20
    elif salario <= 700:
        percentual_aumento = 15
    elif salario <= 1500:
        percentual_aumento = 10
    else:
        percentual_aumento = 5

    aumento = salario * percentual_aumento / 100
    novo_salario = salario + aumento

    return percentual_aumento, aumento, novo_salario

    salario = float(input("Digite o salário do colaborador: R$ "))

    percentual_aumento, aumento, novo_salario = calcular_aumento(salario)

    print(f"Salário antes do reajuste: R$ {salario:.2f}")
    print(f"Percentual de aumento aplicado: {percentual_aumento}%")
    print(f"Valor do aumento: R$ {aumento:.2f}")
    print(f"Novo salário, após o aumento: R$ {novo_salario:.2f}")

"""12. Faça um Programa que leia um número e exiba o dia correspondente da semana.
(1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido.
"""

numero = int(input("Digite um número de 1 a 7: "))

if numero == 1:
        print("Domingo")
elif numero == 2:
        print("Segunda-feira")
elif numero == 3:
        print("Terça-feira")
elif numero == 4:
        print("Quarta-feira")
elif numero == 5:
        print("Quinta-feira")
elif numero == 6:
        print("Sexta-feira")
elif numero == 7:
        print("Sábado")
else:
        print("Valor inválido. Por favor, digite um número entre 1 e 7.")

"""13. Faça um programa que pergunte ao usuário se ele quer passar uma temperatura de
Fahrenheit para Celsius ou de Celsius para Fahrenheit, e que, a partir da resposta
do usuário, faça a devida conversão.
"""

def fahrenheit_para_celsius(fahrenheit):
    celsius = (fahrenheit - 32) * 5/9
    return celsius

def celsius_para_fahrenheit(celsius):
    fahrenheit = (celsius * 9/5) + 32
    return fahrenheit

def main():
    escolha = input("Você quer converter de Fahrenheit para Celsius (digite 'F') ou de Celsius para Fahrenheit (digite 'C')? ").upper()

    if escolha == 'F':
        fahrenheit = float(input("Digite a temperatura em Fahrenheit: "))
        celsius = fahrenheit_para_celsius(fahrenheit)
        print(f"{fahrenheit} Fahrenheit é igual a {celsius:.2f} Celsius.")
    elif escolha == 'C':
        celsius = float(input("Digite a temperatura em Celsius: "))
        fahrenheit = celsius_para_fahrenheit(celsius)
        print(f"{celsius} Celsius é igual a {fahrenheit:.2f} Fahrenheit.")
    else:
        print("Opção inválida. Por favor, digite 'F' para Fahrenheit para Celsius ou 'C' para Celsius para Fahrenheit.")

if __name__ == "__main__":
    main()

"""14. Faça um programa que receba a idade de uma pessoa e imprima sua condição
(obrigatória, optativa ou proibida), em relação ao ato de votar, conforme
apresentado abaixo:
 Pessoas com idade menor que 16 anos são proibidas de votar (proibido);
 Pessoas com idade igual a 16 e menor que 18 anos não são obrigadas a votar
(optativo);
 Pessoas com idade igual a 18 e menor que 65 anos são obrigadas a votar
(obrigatório);
 Pessoas com idade igual ou maior a 65 anos não são obrigadas a votar (optativo).

"""

voto = float(input("Digite sua idade: "))

if voto>= 65 :
  print("Não são obrigadas a votar!")
elif voto >=17:
  print("Optativo!")
else:
  print("Proibido votar!")

"""15. Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As
perguntas são:
 “Telefonou para a vítima? “
 “Esteve no local do crime?”
 “Mora perto da vítima? “
 “Devia para a vítima? “
 “Já trabalhou com a vítima? “
"""

prg = stg(input("Telefonou para a vítima?"))
prg2 = stg(input("Esteve no local do crime?"))
prg3 = stg(input("Mora perto da vítima?"))
prg4 = stg(input("Devia para a vítima?"))
prg5 = stg(input("Já trabalhou com a vítima?"))