# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dnspjoc2-K64J0bFPd49fMeGmN3ib9_W
"""

X=float

para cont x até 4
Leia(x)
R<-x*12
Escreva(R)
fim_para

fim

for f in range(5):
  x= float(input("Digite um valor para X:"))

  r = x *3

  print("O valor de R é:",r)

"""x"""