# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

x=4
x1= 9
x2 = 5


xResult = (((2 + 5) * 3) + x+ 5 )< x1
print (xResult)


xResult = (((2 + 5 ) * 3 ) + (x+5 + x1) == ( x == 6 + x2 * 2))
print (xResult)

xResult = (((3 * 6 ) + x - 3 ) < x2)
print (xResult)

xResult = (((7 * 8 ) > (x+4 > x1) < (x * 2 + x2 * 9 )))
print ( xResult)

n = 32
Nresult = n <=19 or n >= 31
print (Nresult)

a = 11
b = 4
abResult = a > 10 and b <= 5
print (abResult)

a= 11
b=4
abResult = not(a > 10 or b <= 5)
print (abResult)