# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/114fiu24w6TfZPC8RdF151F3T_XIXT6SF
"""

X = 6 + (4 * 2)
print (X)

X = ((4 * 9) + 5)
print (X)

X = ((6 + 7) *9)
print (X)

X = (15 + 20 - 30)
print (X)

X = (6 + (5**2))
print (X)

x = 8
print (x)

x+= 5
print (x)

x-= 4
print (x)

x*= 20
print (x)

x /= 2
print (x)

x = 8
x1 = 3

x_resultado = x < x1
print(x_resultado)

x_resultado = x == x1
print(x_resultado)


x_resultado = x >= x1
print(x_resultado)

x_resultado = x! = x1
print(x_resultado)

x1 = "botafogo"
x2 = "flamengo"
x3 = "botafogo"

Xresultado = x1 is x3
print (Xresultado)

Xresultado = x1 is not x2
print (Xresultado)

Xresultado = x1 is x2
print (Xresultado)

Xresultado = x2 is not x3
print (Xresultado)

frutas = ["banana", "laranja", "uva", "ameixa"]

x1 = "banana"
x2 = "laranja"
x3 = "abacaxi"

xResult = x1 in frutas
print(xResult)

xResult = x1 not in frutas
print(xResult)

xResult = x2 not in frutas
print(xResult)

xResult = x3 in frutas
print(xResult)